# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unicode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unicode.proto',
  package='unh.cs',
  syntax='proto3',
  serialized_pb=_b('\n\runicode.proto\x12\x06unh.cs\"\x14\n\x07Unicode\x12\t\n\x01n\x18\x01 \x01(\t\"\x1f\n\x0c\x43onfirmation\x12\x0f\n\x07message\x18\x01 \x01(\t2@\n\x06Sender\x12\x36\n\x0bSendUnicode\x12\x0f.unh.cs.Unicode\x1a\x14.unh.cs.Confirmation\"\x00\x42\x14\n\x02wsB\x0cUnicodeProtoH\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UNICODE = _descriptor.Descriptor(
  name='Unicode',
  full_name='unh.cs.Unicode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='unh.cs.Unicode.n', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=45,
)


_CONFIRMATION = _descriptor.Descriptor(
  name='Confirmation',
  full_name='unh.cs.Confirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='unh.cs.Confirmation.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['Unicode'] = _UNICODE
DESCRIPTOR.message_types_by_name['Confirmation'] = _CONFIRMATION

Unicode = _reflection.GeneratedProtocolMessageType('Unicode', (_message.Message,), dict(
  DESCRIPTOR = _UNICODE,
  __module__ = 'unicode_pb2'
  # @@protoc_insertion_point(class_scope:unh.cs.Unicode)
  ))
_sym_db.RegisterMessage(Unicode)

Confirmation = _reflection.GeneratedProtocolMessageType('Confirmation', (_message.Message,), dict(
  DESCRIPTOR = _CONFIRMATION,
  __module__ = 'unicode_pb2'
  # @@protoc_insertion_point(class_scope:unh.cs.Confirmation)
  ))
_sym_db.RegisterMessage(Confirmation)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\002wsB\014UnicodeProtoH\003'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class SenderStub(object):
    """[START services]

    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.SendUnicode = channel.unary_unary(
          '/unh.cs.Sender/SendUnicode',
          request_serializer=Unicode.SerializeToString,
          response_deserializer=Confirmation.FromString,
          )


  class SenderServicer(object):
    """[START services]

    """

    def SendUnicode(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_SenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SendUnicode': grpc.unary_unary_rpc_method_handler(
            servicer.SendUnicode,
            request_deserializer=Unicode.FromString,
            response_serializer=Confirmation.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'unh.cs.Sender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaSenderServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """[START services]

    """
    def SendUnicode(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaSenderStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """[START services]

    """
    def SendUnicode(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    SendUnicode.future = None


  def beta_create_Sender_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('unh.cs.Sender', 'SendUnicode'): Unicode.FromString,
    }
    response_serializers = {
      ('unh.cs.Sender', 'SendUnicode'): Confirmation.SerializeToString,
    }
    method_implementations = {
      ('unh.cs.Sender', 'SendUnicode'): face_utilities.unary_unary_inline(servicer.SendUnicode),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Sender_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('unh.cs.Sender', 'SendUnicode'): Unicode.SerializeToString,
    }
    response_deserializers = {
      ('unh.cs.Sender', 'SendUnicode'): Confirmation.FromString,
    }
    cardinalities = {
      'SendUnicode': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'unh.cs.Sender', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
