# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import numbers_pb2 as numbers__pb2


class SenderStub(object):
  """[START services]

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendNumbers = channel.unary_unary(
        '/unh.cs.Sender/SendNumbers',
        request_serializer=numbers__pb2.Numbers.SerializeToString,
        response_deserializer=numbers__pb2.Confirmation.FromString,
        )


class SenderServicer(object):
  """[START services]

  """

  def SendNumbers(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SenderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendNumbers': grpc.unary_unary_rpc_method_handler(
          servicer.SendNumbers,
          request_deserializer=numbers__pb2.Numbers.FromString,
          response_serializer=numbers__pb2.Confirmation.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'unh.cs.Sender', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
