/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'warren' at '10/13/16 1:43 PM' with Gradle 3.1
 *
 * @author warren, @date 10/13/16 1:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
